'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const uid=()=>{const a=new Uint32Array(4);crypto.getRandomValues(a);return Array.from(a,n=>n.toString(16)).join('');};
const dateFmt=s=>s&&/^\d{4}-\d{2}-\d{2}$/.test(s)?s.split('-').reverse().join('.'):'Не указана';
const parseRuDate=value=>{const m=String(value||'').trim().match(/^(\d{2})\.(\d{2})\.(\d{4})$/);if(!m)return null;const d=+m[1],month=+m[2],y=+m[3];return Dictation.dateValid(y,month,d)?`${m[3]}-${m[2]}-${m[1]}`:null;};
const clone=o=>JSON.parse(JSON.stringify(o));
const icons={folder:'<path d="M3 6h6l2 2h10v12H3z"/><path d="M3 6V4h7l2 2"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',mic:'<rect x="8" y="2" width="8" height="13" rx="4"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>',table:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18M9 4v16M15 10v10M3 15h18"/>',shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z"/><path d="m8 12 3 3 5-6"/>',arrow:'<path d="m9 5 7 7-7 7"/>',back:'<path d="m14 5-7 7 7 7M7 12h14"/>',note:'<path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h4"/>',photo:'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="2"/><path d="m3 17 5-4 4 3 4-6 5 7"/>',check:'<path d="m5 12 4 4L19 6"/>',settings:'<circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',edit:'<path d="m4 15 11-11 5 5L9 20l-6 1zM13 6l5 5"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4M12 14v3"/>',stop:'<rect x="5" y="5" width="14" height="14" rx="2"/>'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[n]||icons.note}</svg>`;
const btn=(text,action,cls='',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${text}</button>`;
const options=(list,value)=>list.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x||'Выберите')}</option>`).join('');
const input=(label,path,value,type='text',extra='')=>`<div class="field"><label for="f-${path}">${label}</label><input id="f-${path}" type="${type}" data-path="${path}" value="${esc(value)}" ${extra}></div>`;
const area=(label,path,value,extra='')=>`<div class="field"><label for="f-${path}">${label}</label><textarea id="f-${path}" data-path="${path}" ${extra}>${esc(value)}</textarea></div>`;
const select=(label,path,list,value)=>`<div class="field"><label for="f-${path}">${label}</label><select id="f-${path}" data-path="${path}">${options(list,value)}</select></div>`;
let db={version:1,patients:[],visits:[],draft:null,settings:{intro:false,lastBackup:null}},page='home',selected=null,editPatient=null,patientForm=null,query='',filters={query:'',type:'',from:'',to:''},voiceActive=false,voiceTarget='visit',saveTimer=null,modalKind=null,loadError=false;
let N=window.Native;
const isWebPreview=!!window.__WEB_PREVIEW__;
if(!N){$('#app').innerHTML='<div class="loading"><h2>Карта косметолога</h2><p>Это интерфейс Android-приложения. Для работы установите APK на телефон.</p></div>';}
else{try{const raw=N.load();if(raw){const parsed=JSON.parse(raw);if(parsed.error)throw Error(parsed.error);validateDb(parsed);db=parsed;}render();if(!db.settings.intro)intro();}catch(e){loadError=true;$('#app').innerHTML='<div class="loading"><h2>Картотека не открылась</h2><p>Не удаляйте приложение. Повторно откройте его. Если проблема сохраняется, сохраните резервную копию и обратитесь к разработчику.</p><p class="error">'+esc(e.message)+'</p></div>';}}

function validateDb(x){
 if(!x||x.version!==1||!Array.isArray(x.patients)||!Array.isArray(x.visits)||!x.settings||typeof x.settings!=='object')throw Error('Неподдерживаемый формат картотеки');
 if(x.patients.length>20000||x.visits.length>100000)throw Error('Слишком большая картотека');
 const ids=new Set();for(const p of x.patients){if(!p||typeof p.id!=='string'||ids.has(p.id)||typeof p.name!=='string'||!p.name.trim())throw Error('Ошибка карточек пациентов');ids.add(p.id);}
 const visits=new Set();for(const v of x.visits){if(!v||typeof v.id!=='string'||visits.has(v.id)||!ids.has(v.patientId)||!Array.isArray(v.procedures)||!Array.isArray(v.photos)||!Array.isArray(v.audit))throw Error('Ошибка истории посещений');visits.add(v.id);if(typeof v.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v.date)||v.procedures.some(p=>!p||typeof p.type!=='string'||typeof p.drug!=='string'))throw Error('Ошибка записи процедуры');for(const p of v.photos){if(!p||typeof p.data!=='string'||!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(p.data))throw Error('Ошибка фотографии');}}
 if(x.draft&&(!ids.has(x.draft.patientId)||!Array.isArray(x.draft.procedures)||!Array.isArray(x.draft.photos)))throw Error('Ошибка черновика');
}
function persist(){if(loadError)return false;const r=N.save(JSON.stringify(db));if(r!=='ok'){toast(r||'Не удалось сохранить');return false;}return true;}
function transaction(fn){flushDraft();const before=clone(db);fn();if(!persist()){db=before;return false;}return true;}
function flushDraft(){if(saveTimer){clearTimeout(saveTimer);saveTimer=null;persist();}}
function toast(s){const t=$('#toast');t.textContent=s;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',4500);}
function stopVoice(){N.stopVoice();voiceActive=false;}
function go(p,id){stopVoice();flushDraft();closeModal();page=p;if(id)selected=id;render();window.scrollTo(0,0);}
function initials(name){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function patient(id){return db.patients.find(p=>p.id===id);}
function visitsFor(id){return db.visits.filter(v=>v.patientId===id).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt));}
function nav(){return `<nav class="nav" aria-label="Навигация">${[['home','folder','Картотека'],['new','mic','Запись'],['table','table','Таблица'],['settings','shield','Хранение']].map(([p,i,l])=>`<button data-action="nav" data-page="${p}" class="${page===p||p==='home'&&page==='patient'?'active':''}">${icon(i)}${l}</button>`).join('')}</nav>`;}
function render(){
 const content={home:home,patient:profile,new:visitForm,table:tablePage,settings:settingsPage,visit:visitPage}[page]||home;
 $('#app').innerHTML=`<main class="shell"><div class="topline"><div class="brand">${icon('note')} Карта косметолога</div><span class="offline">${isWebPreview?'Веб-предпросмотр':'На телефоне'}</span></div>${content()}</main>${nav()}`;
}
function home(){return `<div class="heading"><div><h1>Картотека</h1><p class="subtitle">Вся история заботы — под рукой.</p></div><button class="icon-button" data-action="patientNew" aria-label="Добавить пациента">${icon('plus')}</button></div><div class="stats"><div class="stat"><strong>${db.patients.length}</strong><span>пациентов в картотеке</span></div><div class="stat"><strong>${db.visits.length}</strong><span>сохранённых посещений</span></div></div>${db.draft?`<div class="draft-banner"><p>Есть незавершённая запись: ${esc(patient(db.draft.patientId)?.name||'пациент')}. Черновик сохранён ${isWebPreview?'в браузере':'на телефоне'}.</p>${btn('Продолжить запись','resume','small secondary')}</div>`:''}<div class="search">${icon('search')}<input id="search" data-search="home" value="${esc(query)}" placeholder="Имя, телефон или номер карты" aria-label="Поиск пациента"></div><div class="section-label"><span>Пациенты</span>${btn('+ Добавить','patientNew','small outline')}</div><div id="patient-list">${patientList()}</div><div class="pilot"><strong>Редактируемая версия 0.2</strong><br>${isWebPreview?'Веб-режим хранит только учебные данные в этом браузере.':'Проверяйте обновление сначала на вымышленных пациентах.'} Готовность для реальных медицинских данных требует отдельного аудита.</div>`;}
function patientList(){const q=query.toLocaleLowerCase('ru').trim();const items=db.patients.filter(p=>[p.name,p.phone,p.number].some(v=>String(v||'').toLocaleLowerCase('ru').includes(q))).sort((a,b)=>a.name.localeCompare(b.name,'ru'));if(!items.length)return `<div class="empty"><div class="empty-art">${icon('folder')}</div><h3>${q?'Никого не нашли':'Первый пациент — первый шаг'}</h3><p>${q?'Попробуйте другую фамилию, имя или телефон.':'Добавьте учебную карточку, затем надиктуйте результат приёма.'}</p>${q?'':btn('Добавить пациента','patientNew')}</div>`;return `<div class="patients-grid">${items.map(p=>{const last=visitsFor(p.id)[0];return `<button class="patient" data-action="patient" data-id="${esc(p.id)}"><span class="avatar">${esc(initials(p.name))}</span><span class="info"><h3>${esc(p.name)}</h3><p>Карта № ${esc(p.number)}${last?' · '+dateFmt(last.date):' · Нет посещений'}</p>${last?`<p>${esc(last.procedures.map(x=>x.type).join(' · '))}</p>`:''}</span><span class="chevron">${icon('arrow')}</span></button>`;}).join('')}</div>`;}
function profile(){const p=patient(selected);if(!p){page='home';return home();}const vs=visitsFor(p.id);return `<button class="back" data-action="home">${icon('back')} Картотека</button><div class="profile-head"><span class="avatar big">${esc(initials(p.name))}</span><div><h1>${esc(p.name)}</h1><p class="subtitle">Карта № ${esc(p.number)}</p></div></div><div class="actions">${btn(icon('mic')+' Записать приём','newVisit')}${btn(icon('edit'),'patientEdit','outline','aria-label="Изменить карточку"')}</div><div class="card"><dl class="detail"><div><dt>Телефон</dt><dd>${esc(p.phone||'Не указан')}</dd></div><div><dt>Дата рождения</dt><dd>${dateFmt(p.birth)}</dd></div><div class="wide"><dt>Важные сведения со слов специалиста</dt><dd>${esc(p.notes||'Не заполнены')}</dd></div></dl></div><div class="section-label"><span>История посещений · ${vs.length}</span></div>${vs.length?vs.map(v=>visitCard(v)).join(''):`<div class="empty"><h3>История начинается здесь</h3><p>После приёма нажмите «Записать приём» и внесите сведения голосом или вручную.</p></div>`}${vs.length?`<div class="actions">${btn(icon('download')+' История в PDF','pdf','outline')}${btn('Сравнить фото','compare','outline')}</div>`:''}`;}
function visitCard(v){return `<div class="card visit-card"><div class="visit-date">${dateFmt(v.date)}${v.updatedAt?' · исправлена':''}</div><h3>${esc(v.procedures.map(x=>x.type).join(' · '))}</h3><div class="tags">${v.procedures.map(p=>`<span class="tag">${esc(p.drug||'Без препарата')}${p.amount?' · '+esc(p.amount)+' '+esc(p.unit):''}</span>`).join('')}</div><p class="hint">${esc(v.procedures.map(p=>p.zone).filter(Boolean).join('; '))}</p>${v.control?`<p class="hint">Контроль: ${dateFmt(v.control)}</p>`:''}<div class="actions">${btn('Открыть запись','visit','small outline',`data-id="${esc(v.id)}"`)}</div></div>`;}
function blankProcedure(){return {type:'',drug:'',amount:'',unit:'',zone:'',distribution:'',batch:'',expiry:''};}
function newVisit(){if(db.draft){modal(`<h2>Есть незавершённая запись</h2><p>Продолжить её или удалить черновик и начать новый приём?</p><div class="actions">${btn('Продолжить','resume')}${btn('Начать новый','replaceDraft','outline')}</div>`);return;}chooseOrStart();}
function chooseOrStart(){if(page==='patient'&&patient(selected)){startDraft(selected);return;}if(!db.patients.length){toast('Сначала добавьте пациента');showPatientForm();return;}modal(`<h2>Чей приём записываем?</h2><p>Выберите пациента, затем включите микрофон.</p><div class="field"><label for="choose-patient">Пациент и номер карты</label><select id="choose-patient">${db.patients.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} · № ${esc(p.number)}</option>`).join('')}</select></div><div class="actions">${btn('Продолжить','startSelected')}${btn('Отмена','close','outline')}</div>`);}
function startDraft(id){if(!patient(id))return;db.draft={id:uid(),patientId:id,date:today(),procedures:[blankProcedure()],notes:'',control:'',photos:[],transcript:'',audit:[],createdAt:new Date().toISOString(),confirmed:false,editId:null};if(persist())go('new',id);}
function procedureForm(p,i){return `<section class="procedure"><div class="row"><h3>Процедура ${i+1}</h3>${i>0?btn('Убрать','removeProcedure','small outline',`data-index="${i}"`):''}</div>${select('Вид процедуры *',`procedures.${i}.type`,['','Ботулинотерапия','Введение филлера','Биоревитализация','Другое'],p.type)}${input('Точное название и вариант препарата *',`procedures.${i}.drug`,p.drug,'text','maxlength="150" placeholder="Проверьте по упаковке"')}<div class="grid2">${input('Количество *',`procedures.${i}.amount`,p.amount,'text','inputmode="decimal" maxlength="20" placeholder="Например, 1,0"')}${select('Единица *',`procedures.${i}.unit`,['','мл','ед.','мг','другое'],p.unit)}</div>${input('Зона и сторона *',`procedures.${i}.zone`,p.zone,'text','maxlength="250" placeholder="Точно как в вашей записи"')}${area('Распределение по зонам, дополнительные детали',`procedures.${i}.distribution`,p.distribution,'maxlength="2000"')}<div class="grid2">${input('Серия',`procedures.${i}.batch`,p.batch,'text','maxlength="100"')}${input('Годен до',`procedures.${i}.expiry`,p.expiry,'date')}</div></section>`;}
function visitForm(){const d=db.draft;if(!d){page='home';return home();}const p=patient(d.patientId);return `<button class="back" data-action="draftBack">${icon('back')} Сохранить черновик и выйти</button><h1>${d.editId?'Исправление записи':'Новая запись'}</h1><p class="subtitle">${esc(p?.name)} · карта № ${esc(p?.number)}</p><div class="mic-panel"><h3>Расскажите о приёме</h3><p>Говорите короткими фразами: дата, процедура, препарат, количество, зона. Можно просто напечатать текст ниже.</p>${btn(icon('mic')+' Начать диктовку','voice','full','id="voice-button"')}<div id="voice-status" class="live" aria-live="polite">Русская речь · без интернета · до 3 минут</div></div><div class="card"><div class="card-title">${icon('note')} Текст диктовки</div>${area('Исходный текст — можно исправить','transcript',d.transcript,'maxlength="12000" placeholder="25 апреля 2026 года. Введение филлера. Препарат … Количество … Зона …"')}<div class="actions">${btn('Разобрать по полям','parse','secondary')}</div><p class="hint">Разбор помогает с явными датами и количествами. Сложную диктовку и названия препаратов нужно проверить вручную.</p><div id="parse-feedback"></div></div><div class="card"><div class="card-title">${icon('clock')} Сведения о посещении</div>${input('Дата процедуры *','date',d.date,'date')}<p class="hint">По умолчанию — сегодня. Если описываете прошлый приём, измените дату.</p>${d.procedures.map(procedureForm).join('')}<div class="actions">${btn(icon('plus')+' Ещё процедура','addProcedure','outline full')}</div>${area('Наблюдения, реакции, рекомендации специалиста','notes',d.notes,'maxlength="6000" placeholder="Если сведений нет, оставьте поле пустым"')}${input('Назначенный контрольный визит','control',d.control,'date')}</div><div class="card"><div class="card-title">${icon('photo')} Фотографии посещения</div><p class="hint">Для пилота используйте учебные изображения. Фото будут уменьшены и сохранены в картотеке.</p><div class="photo-grid">${d.photos.map((p,i)=>`<figure class="photo"><img src="${esc(p.data)}" alt="Фото посещения ${i+1}">${select('Этап',`photos.${i}.label`,['До','После','Контроль'],p.label)}${btn('Убрать фото','removePhoto','small outline',`data-index="${i}"`)}</figure>`).join('')}</div><div class="actions">${btn(icon('plus')+' Прикрепить фото','photo','outline')}</div></div><div class="sticky-save"><div class="notice">Проверьте пациента, дату, препарат, количество, единицы и зоны. Приложение не определяет дозировки и не назначает лечение.</div><label class="check"><input type="checkbox" id="confirmed" ${d.confirmed?'checked':''}>Я проверила пациента и все сведения о процедурах.</label><div id="form-error" class="error" role="alert"></div>${btn(icon('check')+' Подтвердить и сохранить','saveVisit','full')}<div class="actions">${btn('Удалить черновик','discardDraft','outline')}</div><p class="footer-note">Черновик автоматически сохраняется на этом телефоне.</p></div>`;}
function visitPage(){const v=db.visits.find(x=>x.id===selected);if(!v){page='home';return home();}const p=patient(v.patientId);return `<button class="back" data-action="visitPatient" data-id="${esc(v.patientId)}">${icon('back')} ${esc(p.name)}</button><h1>Приём ${dateFmt(v.date)}</h1><p class="subtitle">Карта № ${esc(p.number)} · запись подтверждена</p>${v.procedures.map((pr,i)=>`<div class="card"><h3>${i+1}. ${esc(pr.type)}</h3><dl class="detail">${[['Препарат',pr.drug],['Количество',[pr.amount,pr.unit].filter(Boolean).join(' ')],['Зона и сторона',pr.zone],['Распределение',pr.distribution],['Серия',pr.batch],['Годен до',pr.expiry?dateFmt(pr.expiry):'']].map(([l,t])=>`<div><dt>${l}</dt><dd>${esc(t||'Не указано')}</dd></div>`).join('')}</dl></div>`).join('')}<div class="card"><h3>Наблюдения специалиста</h3><p class="summary-box subtitle">${esc(v.notes||'Не заполнены')}</p><div class="divider"></div><p class="hint">Контрольный визит: ${v.control?dateFmt(v.control):'не указан'}</p>${v.transcript?`<details><summary>Исходная диктовка</summary><p class="summary-box">${esc(v.transcript)}</p></details>`:''}</div>${v.photos.length?`<div class="card"><h3>Фотографии</h3><div class="photo-grid">${v.photos.map(p=>`<figure class="photo"><img src="${esc(p.data)}" alt="${esc(p.label)}"><figcaption>${esc(p.label)} · ${dateFmt(v.date)}</figcaption></figure>`).join('')}</div></div>`:''}<div class="actions">${btn(icon('edit')+' Исправить запись','editVisit','outline')}</div>${v.audit.length?`<div class="card"><h3>История исправлений</h3>${v.audit.slice().reverse().map(a=>`<details><summary>${esc(new Date(a.at).toLocaleString('ru-RU'))} — прежняя версия</summary><p class="summary-box">${esc(a.snapshot.date+'\n'+a.snapshot.procedures.map(p=>[p.type,p.drug,p.amount,p.unit,p.zone,p.distribution].filter(Boolean).join(' · ')).join('\n')+'\n'+(a.snapshot.notes||''))}</p></details>`).join('')}</div>`:''}<p class="footer-note">Внесено ${esc(new Date(v.createdAt).toLocaleString('ru-RU'))}</p>`;}
function filteredRows(){const q=filters.query.toLowerCase();return db.visits.filter(v=>(!filters.from||v.date>=filters.from)&&(!filters.to||v.date<=filters.to)).sort((a,b)=>b.date.localeCompare(a.date)).flatMap(v=>v.procedures.map(p=>({v,p,person:patient(v.patientId)}))).filter(r=>(!filters.type||r.p.type===filters.type)&&[r.person.name,r.person.number,r.p.drug,r.p.zone].some(s=>String(s||'').toLowerCase().includes(q)));}
function tablePage(){return `<div class="heading"><div><h1>Все процедуры</h1><p class="subtitle">История, которую легко найти.</p></div></div><div class="search">${icon('search')}<input data-filter="query" value="${esc(filters.query)}" placeholder="Пациент, препарат, зона" aria-label="Поиск по процедурам"></div><div class="filters"><div><label for="from">С даты</label><input id="from" type="date" data-filter="from" value="${esc(filters.from)}"></div><div><label for="to">По дату</label><input id="to" type="date" data-filter="to" value="${esc(filters.to)}"></div></div><label for="type-filter">Процедура</label><select id="type-filter" data-filter="type">${options(['','Ботулинотерапия','Введение филлера','Биоревитализация','Другое'],filters.type)}</select><div class="section-label"><span id="row-count">${filteredRows().length} записей</span>${btn(icon('download')+' Excel / CSV','csv','small outline')}</div><p class="hint">Таблицу можно прокручивать вправо.</p><div id="table-content">${tableContent()}</div>`;}
function tableContent(){const rows=filteredRows();if(!rows.length)return `<div class="empty"><h3>Нет записей</h3><p>Измените фильтры или сохраните первый приём.</p></div>`;return `<div class="table-wrap"><table><thead><tr>${['Дата','Пациент','Процедура','Препарат','Количество','Зона'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(({v,p,person})=>`<tr><td><button class="table-link" data-action="visit" data-id="${esc(v.id)}">${dateFmt(v.date)}</button></td><td>${esc(person.name)}<br><span class="mini">№ ${esc(person.number)}</span></td><td>${esc(p.type)}</td><td>${esc(p.drug)}</td><td>${esc([p.amount,p.unit].filter(Boolean).join(' '))}</td><td>${esc(p.zone)}</td></tr>`).join('')}</tbody></table></div>`;}
function settingsPage(){const storage=isWebPreview?`<div class="notice">Веб-предпросмотр предназначен только для вымышленных данных. Они находятся в локальном хранилище браузера и не защищены хранилищем ключей Android.</div><div class="settings-row">${icon('shield')}<div><strong>Учебные данные в браузере</strong><p>Используйте режим для изменения интерфейса и сценариев. Не вводите ФИО и медицинские сведения реальных людей.</p></div></div>`:`<div class="settings-row">${icon('shield')}<div><strong>Данные на этом телефоне</strong><p>База и фотографии зашифрованы ключом Android Keystore. Приложение не имеет разрешения на доступ в интернет.</p></div></div><div class="settings-row">${icon('lock')}<div><strong>Вход с защитой телефона</strong><p>При запуске и после минуты в фоне требуется код или биометрия телефона. Скриншоты теперь разрешены по вашему запросу.</p></div></div>${btn('Заблокировать сейчас','lock','outline full')}`;return `<h1>Хранение и копии</h1><p class="subtitle">Картотека принадлежит вам.</p><div class="card">${storage}</div><div class="card"><div class="card-title">${icon('download')} Резервная копия</div><p class="hint">Копия включает карточки, посещения и фотографии. Сохраните её отдельно от телефона. Без копии данные потеряются при удалении приложения или поломке телефона.</p><div class="notice">Пароль копии нужен для восстановления. Он не связан с PIN-кодом телефона и не может быть восстановлен нами.</div><div class="actions">${btn('Создать копию','backup')}${btn('Восстановить','restore','outline')}</div><p class="hint">Последний успешный экспорт копии: ${db.settings.lastBackup?esc(new Date(db.settings.lastBackup).toLocaleString('ru-RU')):'ещё не создавали'}</p></div><div class="card"><h3>Для первого знакомства</h3><p class="hint">Добавьте две учебные карточки с вымышленными сведениями и посмотрите, как выглядит история.</p><div class="actions">${btn('Добавить учебные карточки','demo','secondary')}</div></div><div class="card"><h3>О тестовой версии</h3><ul class="short-list"><li><strong>Работает без ChatGPT и подписок</strong>${isWebPreview?'Браузер использует доступное системное распознавание речи; при его отсутствии остаётся ручной ввод.':'Русская речь распознаётся на устройстве моделью Vosk. Первый запуск диктовки подготавливает модель.'}</li><li><strong>Диктовка требует проверки</strong>ФИО, телефоны, названия препаратов, даты и числа могут распознаваться неверно. Автоматический разбор ограничен явными подписями полей.</li><li><strong>Только учебные данные</strong>Проект не прошёл юридический, клинический и независимый аудит безопасности для реальных медицинских данных.</li><li><strong>Версия 0.2-source</strong>Android 8 и новее. Модель: vosk-model-small-ru-0.22. Vosk и модель: Apache 2.0; JNA: Apache 2.0.</li></ul></div>`;}
function modal(html,kind=''){modalKind=kind;$('#modal').innerHTML=`<div class="modal-backdrop"><section class="modal-card" role="dialog" aria-modal="true"><div class="row"><span class="brand">Карта косметолога</span><button class="icon-button" data-action="close" aria-label="Закрыть">×</button></div>${html}</section></div>`;}
function closeModal(){if(voiceTarget==='patient'&&voiceActive)stopVoice();modalKind=null;$('#modal').innerHTML='';}
function intro(){modal(`<div class="empty-art">${icon('folder')}</div><h2>Знакомьтесь с картотекой</h2><p>Создайте учебного пациента, надиктуйте его карточку и процедуру, затем проверьте распознанные сведения.</p><div class="notice">Используйте только вымышленные сведения и учебные фотографии, особенно в браузерном предпросмотре.</div><div class="actions">${btn('Начать тестирование','intro')}</div>`,'intro');}
function birthInput(){return `<div class="field"><label for="patient-birth-text">Дата рождения</label><input id="patient-birth-text" type="text" inputmode="numeric" autocomplete="off" maxlength="10" placeholder="ДД.ММ.ГГГГ" data-path="patient.birthText" value="${esc(patientForm.birthText||'')}"><div class="calendar-extra"><span>или выбрать:</span><input id="patient-birth-calendar" type="date" data-calendar="patient-birth" value="${esc(patientForm.birth||'')}" aria-label="Выбрать дату рождения в календаре"></div><p class="hint">Можно сразу напечатать, например: 23.01.1975. Календарь — дополнительная опция.</p></div>`;}
function patientModalHtml(){return `<h2>${editPatient?'Карточка пациента':'Новый пациент'}</h2><div class="mic-panel patient-mic"><h3>Надиктовать карточку</h3><p>Произнесите подписи полей: «ФИО … Дата рождения … Телефон … Примечание …».</p>${btn(icon('mic')+' Начать диктовку','patientVoice','full','id="patient-voice-button"')}<div id="patient-voice-status" class="live" aria-live="polite">После диктовки проверьте исходный текст и каждое поле</div></div>${area('Исходный текст диктовки','patient.voiceText',patientForm.voiceText||'','maxlength="6000" placeholder="ФИО Петрова Екатерина Ивановна. Дата рождения 25 апреля 1985 года. Телефон … Примечание …"')}<div class="actions">${btn('Разобрать карточку по полям','patientParse','secondary')}</div><div id="patient-parse-feedback"></div>${input('ФИО или учебное имя *','patient.name',patientForm.name,'text','maxlength="180" autocomplete="off"')}${input('Телефон','patient.phone',patientForm.phone,'tel','maxlength="40" autocomplete="off"')}${birthInput()}${area('Важные сведения — заполняет специалист','patient.notes',patientForm.notes,'maxlength="4000"')}<label class="check"><input type="checkbox" id="patient-confirmed" ${patientForm.confirmed?'checked':''}>Я проверила ФИО, дату рождения, телефон и остальные сведения.</label><div id="patient-error" class="error"></div><div class="actions">${btn('Сохранить карточку','patientSave')}${btn('Отмена','close','outline')}</div>`;}
function showPatientModal(){modal(patientModalHtml(),'patient');updateVoice();}
function showPatientForm(id){editPatient=id||null;const base=id?clone(patient(id)):{name:'',birth:'',phone:'',notes:''};patientForm={...base,birthText:base.birth?dateFmt(base.birth):'',voiceText:'',confirmed:false};voiceTarget='patient';showPatientModal();}
function savePatient(){const p=patientForm;if(!p.name.trim())return $('#patient-error').textContent='Укажите имя пациента.';const birth=p.birthText.trim()?parseRuDate(p.birthText):'';if(p.birthText.trim()&&!birth)return $('#patient-error').textContent='Введите дату рождения строго в формате ДД.ММ.ГГГГ, например 23.01.1975.';if(birth&&birth>today())return $('#patient-error').textContent='Дата рождения не может быть в будущем.';if(!p.confirmed)return $('#patient-error').textContent='Подтвердите, что проверили сведения карточки.';let id=editPatient||uid();const clean={name:p.name.trim(),birth,phone:p.phone.trim(),notes:p.notes.trim()};if(transaction(()=>{if(editPatient){Object.assign(patient(id),clean,{updatedAt:new Date().toISOString()});}else{db.patients.push({...clean,id,number:String(Math.max(0,...db.patients.map(x=>Number(x.number)||0))+1).padStart(4,'0'),createdAt:new Date().toISOString()});}})){closeModal();go('patient',id);toast('Карточка сохранена');}}
function parsePatientVoice(){stopVoice();if(!patientForm.voiceText.trim()){toast('Сначала надиктуйте или напишите учебный текст карточки');return;}const parsed=Dictation.extractPatient(patientForm.voiceText);if((patientForm.name||patientForm.phone||patientForm.birthText||patientForm.notes)&&!confirm('Перенести распознанные сведения? Заполненные совпадающие поля будут заменены.'))return;for(const k of ['name','phone','notes'])if(parsed[k])patientForm[k]=parsed[k];if(parsed.birth){patientForm.birth=parsed.birth;patientForm.birthText=dateFmt(parsed.birth);}patientForm.confirmed=false;showPatientModal();$('#patient-parse-feedback').innerHTML=`<div class="notice">${parsed.warnings.map(esc).join('<br>')}</div>`;}
function setPath(obj,path,value){let parts=path.split('.'),p=obj;for(let i=0;i<parts.length-1;i++){p=p[parts[i]];if(p==null)return;}p[parts[parts.length-1]]=value;}
document.addEventListener('input',e=>{
 const t=e.target;if(t.dataset.search){query=t.value;$('#patient-list').innerHTML=patientList();return;}
 if(t.dataset.filter){filters[t.dataset.filter]=t.value;$('#table-content').innerHTML=tableContent();$('#row-count').textContent=filteredRows().length+' записей';return;}
 const path=t.dataset.path;if(!path)return;
 if(path.startsWith('patient.')){setPath(patientForm,path.slice(8),t.value);patientForm.confirmed=false;if($('#patient-confirmed'))$('#patient-confirmed').checked=false;return;}
 if(db.draft){setPath(db.draft,path,t.value);db.draft.confirmed=false;if($('#confirmed'))$('#confirmed').checked=false;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{saveTimer=null;persist();},600);}
});
document.addEventListener('change',e=>{if(e.target.id==='confirmed'&&db.draft){db.draft.confirmed=e.target.checked;persist();}if(e.target.id==='patient-confirmed'&&patientForm)patientForm.confirmed=e.target.checked;if(e.target.dataset.calendar==='patient-birth'&&patientForm){patientForm.birth=e.target.value;patientForm.birthText=e.target.value?dateFmt(e.target.value):'';patientForm.confirmed=false;if($('#patient-birth-text'))$('#patient-birth-text').value=patientForm.birthText;if($('#patient-confirmed'))$('#patient-confirmed').checked=false;}});
function checkVisit(d){if(!patient(d.patientId))return 'Пациент не найден.';if(!d.date||d.date>today())return 'Укажите корректную дату выполненной процедуры, не в будущем.';for(let i=0;i<d.procedures.length;i++){const p=d.procedures[i],prefix=`Процедура ${i+1}: `;if(!p.type)return prefix+'выберите вид процедуры.';if(p.type!=='Другое'&&(!p.drug.trim()||!p.amount||!p.unit||!p.zone.trim()))return prefix+'заполните препарат, количество, единицу и зону.';if(p.amount&&(!/^\d+(?:[.,]\d+)?$/.test(p.amount)||Number(p.amount.replace(',','.'))<=0))return prefix+'количество должно быть положительным числом, например 0,5.';if(p.amount&&!p.unit)return prefix+'укажите единицу количества.';if(p.unit&&!p.amount)return prefix+'укажите количество.';}if(!d.confirmed)return 'Подтвердите, что проверили пациента и сведения о процедурах.';return '';}
function saveVisit(){stopVoice();const err=checkVisit(db.draft);if(err){$('#form-error').textContent=err;$('#form-error').scrollIntoView({block:'center',behavior:'smooth'});return;}const d=clone(db.draft),id=d.patientId;if(transaction(()=>{if(d.editId){let i=db.visits.findIndex(v=>v.id===d.editId);if(i<0)throw Error('Запись не найдена');const old=db.visits[i];d.id=old.id;d.audit=old.audit.concat([{at:new Date().toISOString(),snapshot:{date:old.date,procedures:clone(old.procedures),notes:old.notes,control:old.control,transcript:old.transcript,photoLabels:old.photos.map(x=>x.label)}}]);d.updatedAt=new Date().toISOString();delete d.editId;delete d.confirmed;db.visits[i]=d;}else{delete d.editId;delete d.confirmed;db.visits.push(d);}db.draft=null;})){go('patient',id);toast('Посещение сохранено');}}
function parse(){stopVoice();flushDraft();const d=db.draft;if(!d.transcript.trim()){toast('Сначала надиктуйте или напишите текст');return;}const parsed=Dictation.extract(d.transcript);if(d.procedures.length>1){toast('В записи несколько процедур. Перенесите сведения в нужные строки вручную.');return;}const p=d.procedures[0];if(Object.values(p).some(Boolean)&&!confirm('Заполнить распознанные поля первой процедуры? Уже заполненные совпадающие поля будут заменены.'))return;for(const k of ['type','drug','amount','unit','zone','batch'])if(parsed[k])p[k]=parsed[k];if(parsed.date)d.date=parsed.date;d.confirmed=false;persist();render();$('#parse-feedback').innerHTML=`<div class="notice">${parsed.warnings.map(esc).join('<br>')}</div>`;$('#parse-feedback').scrollIntoView({block:'center'});}
function csvCell(v){let s=String(v||'');if(/^[\s]*[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
function csv(){const rows=filteredRows();if(!rows.length){toast('Нет записей для экспорта');return;}if(!confirm('CSV содержит сведения пациентов и не зашифрован. Сохранить выбранные записи?'))return;const head=['Дата','Номер карты','Пациент','Процедура','Препарат','Количество','Единица','Зона','Распределение','Серия','Годен до','Наблюдения','Контроль'];const data=[head,...rows.map(({v,p,person})=>[dateFmt(v.date),person.number,person.name,p.type,p.drug,p.amount,p.unit,p.zone,p.distribution,p.batch,dateFmt(p.expiry),v.notes,v.control?dateFmt(v.control):''])];window.exportKind='csv';N.exportCsv('\uFEFF'+data.map(row=>row.map(csvCell).join(';')).join('\r\n'));}
function backupModal(restore){modal(`<h2>${restore?'Восстановить картотеку':'Создать резервную копию'}</h2><p>${restore?'Введите пароль копии, затем выберите файл .karta. Перед заменой текущей картотеки будет запрошено подтверждение.':'Придумайте пароль не короче 10 символов. Сохраните его отдельно: без него восстановление невозможно.'}</p><div class="field"><label for="backup-pass">Пароль резервной копии</label><input id="backup-pass" type="password" autocomplete="new-password" minlength="10"></div>${restore?'':'<div class="field"><label for="backup-repeat">Повторите пароль</label><input id="backup-repeat" type="password" autocomplete="new-password"></div>'}<div id="backup-error" class="error"></div><div class="actions">${btn(restore?'Выбрать файл':'Сохранить файл',restore?'restoreGo':'backupGo')}${btn('Отмена','close','outline')}</div>`);}
function pdf(){const p=patient(selected);if(!p)return;if(!N.printHtml){toast('PDF доступен в Android-приложении');return;}if(!confirm('PDF содержит сведения пациента и не зашифрован. Открыть печать / сохранение в PDF?'))return;const vs=visitsFor(p.id);const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><style>body{font-family:sans-serif;padding:25px;font-size:12px;color:#20382f}h1{font-size:23px}h2{font-size:17px;margin-top:25px}table{width:100%;border-collapse:collapse}td,th{padding:9px;border:1px solid #ddd;text-align:left}p{white-space:pre-wrap;line-height:1.5}small{color:#666}</style><h1>История посещений</h1><p>${esc(p.name)} · карта № ${esc(p.number)}<br>Дата рождения: ${dateFmt(p.birth)}<br>Телефон: ${esc(p.phone||'Не указан')}</p><p>Важные сведения: ${esc(p.notes||'Не заполнены')}</p>${vs.map(v=>`<h2>${dateFmt(v.date)}</h2><table><tr><th>Процедура и препарат</th><th>Количество</th><th>Зона</th></tr>${v.procedures.map(pr=>`<tr><td>${esc(pr.type)}<br>${esc(pr.drug)}<br>Серия: ${esc(pr.batch||'не указана')}<br>Годен до: ${dateFmt(pr.expiry)}</td><td>${esc(pr.amount)} ${esc(pr.unit)}</td><td>${esc(pr.zone)}<br>${esc(pr.distribution)}</td></tr>`).join('')}</table><p>Наблюдения: ${esc(v.notes||'Не заполнены')}<br>Контроль: ${dateFmt(v.control)}</p>`).join('')}<p><small>Экспорт из тестовой версии «Карта косметолога». Фотографии в этот отчёт не включены. Не является автоматически оформленной официальной медицинской картой.</small></p></html>`;N.printHtml(html);}
function addDemo(){if(db.patients.some(p=>p.demo)){toast('Учебные карточки уже добавлены');return;}if(transaction(()=>{const id=uid(),now=new Date().toISOString(),num=Math.max(0,...db.patients.map(x=>Number(x.number)||0));db.patients.push({id,name:'Учебная Анна',number:String(num+1).padStart(4,'0'),birth:'1990-05-15',phone:'',notes:'Вымышленная карточка для знакомства с приложением.',demo:true,createdAt:now},{id:uid(),name:'Учебная Мария',number:String(num+2).padStart(4,'0'),birth:'',phone:'',notes:'Все сведения учебные.',demo:true,createdAt:now});db.visits.push({id:uid(),patientId:id,date:today(),createdAt:now,procedures:[{...blankProcedure(),type:'Введение филлера',drug:'Учебный препарат — не для применения',amount:'1,0',unit:'мл',zone:'Учебная зона',batch:'DEMO-001'}],notes:'Пример структуры записи. Не описание реального лечения.',control:'',photos:[],transcript:'',audit:[]});})){go('home');toast('Учебные карточки добавлены');}}
function compare(){const photos=visitsFor(selected).flatMap(v=>v.photos.map(p=>({...p,date:v.date})));if(photos.length<2){toast('Для сравнения добавьте хотя бы две фотографии в посещения');return;}modal(`<h2>Фотографии пациента</h2><p>Выберите два снимка для сравнения.</p><div class="grid2">${[0,1].map((n)=>`<div class="field"><label for="compare-${n}">Снимок ${n+1}</label><select id="compare-${n}">${photos.map((p,i)=>`<option value="${i}" ${i===n?'selected':''}>${dateFmt(p.date)} · ${esc(p.label)} · ${i+1}</option>`).join('')}</select></div>`).join('')}</div><div class="actions">${btn('Показать','compareShow')}</div><div id="comparison" class="photo-grid"></div>`);window.comparePhotos=photos;showComparison();}
function showComparison(){const a=window.comparePhotos[Number($('#compare-0').value)],b=window.comparePhotos[Number($('#compare-1').value)];$('#comparison').innerHTML=[a,b].map(p=>`<figure class="photo"><img src="${esc(p.data)}" alt="${esc(p.label)}"><figcaption>${dateFmt(p.date)} · ${esc(p.label)}</figcaption></figure>`).join('');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;try{
 if(a==='nav'){if(b.dataset.page==='new')newVisit();else go(b.dataset.page);}
 else if(a==='home')go('home');else if(a==='patient'||a==='visitPatient')go('patient',b.dataset.id);else if(a==='visit')go('visit',b.dataset.id);
 else if(a==='patientNew')showPatientForm();else if(a==='patientEdit')showPatientForm(selected);else if(a==='patientSave')savePatient();else if(a==='close'){if(modalKind==='intro'){db.settings.intro=true;persist();}closeModal();}
 else if(a==='intro'){db.settings.intro=true;persist();closeModal();}else if(a==='newVisit')newVisit();else if(a==='startSelected')startDraft($('#choose-patient').value);
 else if(a==='resume')go('new',db.draft.patientId);else if(a==='replaceDraft'){if(transaction(()=>db.draft=null)){closeModal();chooseOrStart();}}
 else if(a==='draftBack')go('patient',db.draft.patientId);else if(a==='voice'){voiceTarget='visit';flushDraft();N.voice();}else if(a==='patientVoice'){voiceTarget='patient';N.voice();}else if(a==='patientParse')parsePatientVoice();
 else if(a==='parse')parse();else if(a==='addProcedure'){stopVoice();flushDraft();db.draft.procedures.push(blankProcedure());db.draft.confirmed=false;persist();render();}
 else if(a==='removeProcedure'){if(confirm('Убрать эту процедуру из черновика?')){db.draft.procedures.splice(+b.dataset.index,1);db.draft.confirmed=false;persist();render();}}
 else if(a==='discardDraft'){if(confirm('Удалить незавершённый черновик? Подтверждённые посещения сохранятся.')){const id=db.draft.patientId;if(transaction(()=>db.draft=null))go('patient',id);}}
 else if(a==='saveVisit')saveVisit();else if(a==='photo'){flushDraft();if(db.draft.photos.length>=8)toast('В пилоте — до 8 фото на посещение');else N.photo();}
 else if(a==='removePhoto'){if(confirm('Убрать фото из черновика?')){db.draft.photos.splice(+b.dataset.index,1);db.draft.confirmed=false;persist();render();}}
 else if(a==='editVisit'){if(db.draft){toast('Сначала завершите или удалите текущий черновик');return;}const v=db.visits.find(x=>x.id===selected);db.draft={...clone(v),editId:v.id,confirmed:false};persist();go('new',v.patientId);}
 else if(a==='csv')csv();else if(a==='pdf')pdf();else if(a==='backup')backupModal(false);else if(a==='restore')backupModal(true);
 else if(a==='backupGo'||a==='restoreGo'){const pass=$('#backup-pass').value;if(pass.length<10){$('#backup-error').textContent='Пароль должен содержать минимум 10 символов.';return;}if(a==='backupGo'&&pass!==$('#backup-repeat').value){$('#backup-error').textContent='Пароли не совпадают.';return;}flushDraft();if(!persist())return;closeModal();toast('Подготовка файла…');window.exportKind=a==='backupGo'?'backup':'restore';if(a==='backupGo')N.backup(pass);else N.restore(pass);}
 else if(a==='lock'){flushDraft();N.lock();}else if(a==='demo')addDemo();else if(a==='compare')compare();else if(a==='compareShow')showComparison();
 }catch(err){toast('Не удалось выполнить действие. Данные не удалены.');console.error(err);}
});
window.nativeEvent=(type,value)=>{
 if(type==='error'){voiceActive=false;updateVoice();toast(value);return;}
 const status=voiceTarget==='patient'?$('#patient-voice-status'):$('#voice-status');
 if(type==='voiceStart'){voiceActive=true;updateVoice();if(status)status.textContent='Слушаю… После диктовки нажмите «Остановить».';}
 if(type==='voiceStop'){voiceActive=false;updateVoice();if(status)status.textContent='Диктовка завершена. Проверьте текст и разберите его по полям.';}
 if(type==='voiceState'||type==='voicePartial'){if(status)status.textContent=value||'Слушаю…';}
 if(type==='voiceText'&&value.trim()&&voiceTarget==='patient'&&patientForm){patientForm.voiceText=(patientForm.voiceText+' '+value.trim()).trim();patientForm.confirmed=false;const field=$('[data-path="patient.voiceText"]');if(field)field.value=patientForm.voiceText;if($('#patient-confirmed'))$('#patient-confirmed').checked=false;}
 if(type==='voiceText'&&value.trim()&&voiceTarget==='visit'&&db.draft){db.draft.transcript=(db.draft.transcript+' '+value.trim()).trim();db.draft.confirmed=false;if($('#f-transcript'))$('#f-transcript').value=db.draft.transcript;if($('#confirmed'))$('#confirmed').checked=false;persist();}
 if(type==='photo'&&db.draft){if(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(value)){toast('Неверный формат фото');return;}db.draft.photos.push({id:uid(),label:'До',data:value});db.draft.confirmed=false;persist();if(page==='new')render();}
 if(type==='exported'){if(window.exportKind==='backup'){db.settings.lastBackup=new Date().toISOString();persist();if(page==='settings')render();}window.exportKind=null;toast('Файл сохранён');}
 if(type==='restored'){try{const candidate=JSON.parse(value);validateDb(candidate);if(!confirm(`В копии: ${candidate.patients.length} пациентов, ${candidate.visits.length} посещений. Заменить текущую картотеку целиком? Сначала убедитесь, что у вас есть копия текущих данных.`))return;const old=db;db=candidate;if(persist()){go('home');toast('Картотека восстановлена');}else db=old;}catch(e){toast('Копия не прошла проверку. Текущие записи сохранены.');}}
};
function updateVoice(){const id=voiceTarget==='patient'?'#patient-voice-button':'#voice-button',b=$(id);if(b){b.innerHTML=icon(voiceActive?'stop':'mic')+(voiceActive?' Остановить':'Начать диктовку');b.classList.toggle('recording',voiceActive);}}
window.appBack=()=>{if($('#modal').innerHTML){closeModal();return;}if(page==='new'&&db.draft){go('patient',db.draft.patientId);return;}if(page==='visit'){const v=db.visits.find(x=>x.id===selected);go('patient',v?.patientId);return;}if(page!=='home'){go('home');return;}flushDraft();N.quit();};
